#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/0545b3db-f8bb-4af1-a2b1-404dc68995ca 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch switch1;
  CloudSwitch switch2;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define sw1 13
#define sw2 12


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(sw1,OUTPUT);
  pinMode(sw2,OUTPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
}



/*
  Since Switch1 is READ_WRITE variable, onSwitch1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitch1Change()  {
  // Add your code here to act upon Switch1 change
  if(switch1){
    digitalWrite(sw1,LOW);
    Serial.println("Switch ON");
  }else{
    digitalWrite(sw1,HIGH);
    Serial.println("Switch OFF");
  }
  
}

/*
  Since Switch2 is READ_WRITE variable, onSwitch2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitch2Change()  {
  // Add your code here to act upon Switch2 change
   if(switch2){
    digitalWrite(sw2,LOW);
    Serial.println("Switch ON");
  }else{
    digitalWrite(sw2,HIGH);
    Serial.println("Switch OFF");
  }
}




